/* ============================================================
   WILDMAN ROBERTSON — FIREARMS IN STOCK
   Generated from Stock/FIREARMS/Firearm Verification.xlsx
   Last updated: 8 July 2026 (110 units / 92 models)
   NOTE: serial and registration numbers are never published.
   img: null = image not sourced yet (card renders text-only)
   lic: licence-section hint key → hunt | sd | sport (see firearm.html)
   ============================================================ */

/* Shared family content — keeps variants consistent */
var FAM = {
  howaM1500: {
    features: ['Forged one-piece bolt with two-stage HACT trigger', 'Cold hammer-forged Japanese barrel', 'Hogue-style pillar-bedded synthetic stock', 'Threaded muzzle (capped) for brake or suppressor', 'Lifetime action accuracy reputation at a working-rifle price'],
    market: 'The Howa M1500 has quietly become one of South Africa\'s favourite value hunting actions — Japanese build quality, a genuinely good factory trigger, and accuracy that embarrasses rifles at twice the price. A very easy rifle to recommend to first-time hunters.'
  },
  howaM1500HB: {
    features: ['Heavy/varmint contour cold hammer-forged barrel', 'Two-stage HACT match-style trigger', 'Threaded muzzle for brake or suppressor', 'Pillar-bedded synthetic stock', 'Ideal platform for long-range and varmint work'],
    market: 'The heavy-barrel M1500s are the budget precision secret of SA shooting clubs — stiff barrels, honest sub-MOA potential with good ammo, and a bombproof action that gunsmiths love working with.'
  },
  ataTurqua: {
    features: ['Turkish walnut stock with adjustable options', 'Cold hammer-forged 61cm barrel, threaded muzzle', 'Sliding three-position safety', 'Adjustable single-stage trigger', 'Detachable magazine'],
    market: 'The Turqua has won a strong following in SA as the walnut-stocked hunting rifle that undercuts the European names without feeling cheap — reviewers consistently note the smooth action and better-than-expected accuracy.'
  },
  rugerAmGen2: {
    features: ['Gen 2 adjustable stock — comb height & length of pull', 'Spiral-fluted, cold hammer-forged barrel with muzzle brake', 'Ruger Marksman adjustable trigger (3–5 lb)', 'Splatter-finish Cerakote metalwork', 'Three-lug 70° bolt with oversized handle'],
    market: 'The American Gen 2 took the best-selling budget rifle in the US and fixed everything hunters asked for — the adjustable stock and factory brake make it a superbly practical Karoo rifle out of the box. Reviewers rate it the value benchmark in its class.'
  },
  rugerAmRimfire: {
    features: ['Ruger Marksman adjustable trigger', 'Interchangeable comb modules (low for irons, high for scope)', 'Detachable 10/22-pattern rotary magazine', 'Cold hammer-forged barrel', 'Ideal trainer that mirrors the centrefire American'],
    market: 'A favourite first rifle in SA — cheap to feed, accurate, and it shares magazines with the 10/22. The adjustable comb means it grows with the shooter from irons to optics.'
  },
  glock19: {
    features: ['Compact 15+1 9mmP — the global benchmark carry size', 'Legendary reliability with minimal maintenance', 'Safe Action striker system, consistent trigger', 'Massive local parts, holster and gunsmith support', 'Ideal balance of shootability and concealability'],
    market: 'The Glock 19 is the most recommended defensive pistol in South Africa, full stop. Instructors default to it, parts and magazines are everywhere, and resale stays strong. If you ask ten professionals what to buy first, eight say G19.'
  },
  czP09: {
    features: ['DA/SA hammer-fired with decocker (convertible to safety)', 'High capacity 9mmP', 'Renowned CZ ergonomics and pointability', 'Nocturne edition styling and sights', 'Popular IDPA/IPSC production-class choice'],
    market: 'CZ\'s P-09 is the sport shooter\'s favourite duty-size pistol in SA — soft-shooting, accurate, and the DA/SA action gives new shooters a wonderfully forgiving platform. The Nocturne editions have been selling out nationally.'
  },
  panzerSS: {
    features: ['Ultra-compact pump-action 12GA', 'Colour-accented furniture — distinctive range presence', 'Simple, robust Turkish build', 'Excellent value home-defence format', 'Fun, fast-handling package'],
    market: 'Panzer\'s Super Short series has built a cult following locally as an affordable, characterful defensive shotgun — short, light and undeniably fun on the range.'
  },
  pcCarbine: {
    features: ['Takedown design — splits in seconds for transport', 'Interchangeable magazine wells: Ruger AND Glock mags', 'Dead-blow bolt reduces felt recoil', 'Threaded barrel, ghost-ring sights', 'Pairs perfectly with a 9mm pistol'],
    market: 'The PC Carbine is the pistol-calibre carbine most SA dealers recommend — the Glock magazine compatibility is the killer feature, making it the natural range partner for the country\'s most common pistol.'
  }
};

var FIREARMS_STOCK = [
  /* ---- RIFLES — centrefire hunting & precision ---- */
  { id: 'sako-s20-243', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Sako S20 Precision', calibre: '.243 Win', detail: 'Fluted 24.3" barrel, 5/8x24 thread', price: 48999, qty: 1, img: null, lic: 'hunt',
    features: ['Hybrid chassis design — swap between hunter and precision configurations', 'Factory sub-MOA accuracy guarantee', 'Adjustable cheek piece and length of pull', 'Fluted, threaded cold hammer-forged barrel', 'Full aluminium chassis core'],
    market: 'Sako\'s S20 is the thinking hunter\'s crossover — Finnish precision-rifle accuracy in a platform that converts from veld rifle to range rifle. Reviewers consistently call it one of the most accurate factory rifles they\'ve tested.' },
  { id: 'sako-90s-hunter', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Sako 90S Hunter', calibre: '.243 Win', detail: '22.4" barrel, 15x1 thread', price: 48499.99, qty: 1, img: null, lic: 'hunt',
    features: ['Sako 90 series — the newest generation of the legendary Finnish line', 'Premium oiled walnut stock', 'Adjustable single-stage trigger', 'Threaded barrel for brake or suppressor', 'Total Control latch detachable magazine'],
    market: 'The Sako 90 launched as the refinement of everything Sako learned from the 85 — buttery bolt, superb walnut and heirloom build quality. For hunters wanting one rifle for life, this is the shortlist.' },
  { id: 'win-m70-supergrade', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Winchester Model 70 Super Grade', calibre: '.308 Win', detail: 'Classic walnut sporter', price: 46499, qty: 1, img: null, lic: 'hunt',
    features: ['"The Rifleman\'s Rifle" — pre-64 style controlled round feed', 'Massive claw extractor for guaranteed feeding', 'Grade IV/V fancy walnut with ebony forend tip', 'Three-position safety', 'M.O.A. adjustable trigger'],
    market: 'The Model 70 Super Grade is pure classic Americana — collectors and hunters alike praise the controlled-round-feed action and showpiece walnut. A rifle bought as much with the heart as the head, and it never disappoints either.' },
  { id: 'win-m70-safari', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Winchester Model 70 Safari Express', calibre: '.375 H&H Mag', detail: 'Dangerous-game classic', price: 51999, qty: 1, img: null, lic: 'hunt',
    features: ['.375 H&H — the legal minimum and classic choice for African dangerous game', 'Controlled round feed with claw extractor — feeds upside down if it must', 'Express open sights + drilled/tapped for optics', 'Dual steel crossbolts in reinforced walnut stock', 'Three-position safety'],
    market: 'For a buffalo rifle, professional hunters keep coming back to two names — and this is one of them. The Safari Express in .375 H&H is the standard by which working dangerous-game rifles are judged.' },
  { id: 'tikka-t3-hunter-243', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Tikka T3 Hunter', calibre: '.243 Win', detail: 'Walnut stock', price: 35695, qty: 1, img: null, lic: 'hunt',
    features: ['Finnish-built with 1-MOA factory accuracy guarantee', 'Silky 75° bolt lift — among the smoothest factory actions', 'Oiled walnut stock', 'Crisp adjustable single-stage trigger', 'Lightweight for mountain and walk-and-stalk hunts'],
    market: 'Tikka\'s reputation in SA borders on folklore: the rifle that shoots sub-MOA out of the box more consistently than anything near its price. The walnut Hunter is the pick for those who want that accuracy in a rifle that also looks the part.' },
  { id: 'tikka-t3x-hunter-308', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Tikka T3x Hunter', calibre: '.308 Win', detail: 'Walnut stock', price: 35599, qty: 1, img: null, lic: 'hunt',
    features: ['T3x upgrades: improved grip, metal bolt shroud, extra screw spacing for optics', '1-MOA factory accuracy guarantee', 'Smooth 75° bolt, crisp adjustable trigger', 'Oiled walnut stock', '.308 Win — the do-everything SA hunting calibre'],
    market: 'The T3x Hunter in .308 is arguably the most recommended "one rifle for everything" combination in South African gun shops. Accuracy, reliability and resale value are all top-tier.' },
  { id: 'mauser-m18-6xc', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Mauser M18 Chassis', calibre: '6mm XC', detail: '26" threaded barrel', price: 49999, qty: 1, img: null, lic: 'sport',
    features: ['Genuine Mauser action in a competition chassis', '6mm XC — a dedicated precision/target cartridge', '26" threaded barrel for brakes and suppressors', 'Adjustable ergonomics for prone and positional shooting', 'Three-position safety'],
    market: 'A specialist\'s rifle: the 6XC chambering says everything — this is for the long-range and competition crowd, wrapped around the Mauser name and its two centuries of action pedigree.' },
  { id: 'savage-110-elite', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Savage 110 Elite Precision', calibre: '.300 PRC', detail: 'MDT ACC chassis', price: 76999, qty: 1, img: null, lic: 'sport',
    features: ['MDT Adjustable Core Competition (ACC) chassis', 'Factory-blueprinted 110 action', 'User-adjustable AccuTrigger', '.300 PRC — modern king of the 1,000m+ game', 'Adjustable everything: comb, LOP, weights'],
    market: 'This is Savage\'s flagship long-range rifle and the precision community rates it a chassis-rifle bargain: an MDT ACC chassis alone costs a large chunk of the price, and the blueprinted action delivers genuine match accuracy.' },
  { id: 'savage-impulse-300wm', cat: 'rifles', type: 'Straight-Pull Rifle', name: 'Savage Impulse', calibre: '.300 Win Mag', detail: 'Fluted 24" barrel, 5/8x24 thread', price: 47699, qty: 1, img: 'images/firearms/savage-impulse.jpg', lic: 'hunt',
    features: ['American straight-pull action — fastest follow-up shots in bolt guns', 'Hexlock ball-bearing locking system', 'AccuTrigger and AccuFit adjustable stock', 'Fluted, threaded 24" barrel', 'Ambidextrous, reversible bolt handle'],
    market: 'Straight-pulls have taken European hunting by storm and the Impulse brought the concept to a working price. Owners rave about the speed on driven and follow-up shots — a genuinely different experience from a turn-bolt.' },
  { id: 'bergara-b14-hmr', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Bergara B-14 HMR', calibre: '.300 Win Mag', detail: 'Hunting & Match Rifle', price: 28999, qty: 1, img: null, lic: 'hunt',
    features: ['Bergara\'s famous Spanish button-rifled barrel', 'Mini-chassis moulded into the stock for repeatable bedding', 'Adjustable comb and length of pull', 'Sub-MOA factory guarantee', 'Hunting weight with match-rifle stability'],
    market: 'The B-14 HMR is the crossover rifle that made Bergara\'s name — hunters use it on game in winter and steel in summer. Barrel quality is the constant refrain in reviews: these things simply shoot.' },
  { id: 'marlin-1895sbl', cat: 'rifles', type: 'Lever-Action Rifle', name: 'Marlin 1895 SBL', calibre: '.45-70 Govt', detail: 'Stainless, laminate stock', price: 43799.99, qty: 1, img: null, lic: 'hunt',
    features: ['Reborn under Ruger ownership — best-built Marlins ever made', 'Stainless steel with grey laminate furniture', 'Big-loop lever, ghost-ring sight + Picatinny rail', '.45-70 Govt — massive close-range authority', 'Six-round tube magazine'],
    market: 'The new Ruger-made 1895 SBL has been a phenomenon — reviewers who were sceptical of the Marlin revival now call it the best factory lever gun ever produced. Bushveld hunters love the fast handling and sheer stopping power.' },
  { id: 'cz-600-trail', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'CZ 600 Trail', calibre: '.223 Rem', detail: '16" barrel, 15x1 thread', price: 32999, qty: 1, img: null, lic: 'hunt',
    features: ['Ultra-compact PDW-style bolt gun', 'Accepts AR-15 pattern magazines in .223', 'Collapsible/adjustable stock', '16" threaded barrel — suppressor-ready', 'Two-position adjustable trigger'],
    market: 'The 600 Trail is CZ thinking outside the box: a truck gun / trainer / pest rifle that borrows AR ergonomics with bolt-action simplicity. A niche rifle that its owners tend to adore.' },
  { id: 'cz-600-lux', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'CZ 600 Lux', calibre: '.300 Win Mag', detail: '24" barrel, walnut stock', price: 29999.99, qty: 1, img: null, lic: 'hunt',
    features: ['Classic Bavarian-comb walnut stock', 'Adjustable single-stage trigger', 'Fully interchangeable barrel system', '60° bolt throw, controlled cartridge feed', 'Sub-MOA guarantee (3-shot, factory ammo)'],
    market: 'CZ\'s 600 series replaced the beloved 550 and the Lux carries its spirit — old-world walnut looks over a modern guaranteed-accuracy action. Strong value against the European competition.' },
  { id: 'ruger-am-gen2-243', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger American Gen 2', calibre: '.243 Win', detail: 'Model 46904', price: 20499.99, qty: 1, img: 'images/firearms/ruger-american-gen2.jpg', lic: 'hunt', features: FAM.rugerAmGen2.features, market: FAM.rugerAmGen2.market },
  { id: 'ruger-am-gen2-308', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger American Gen 2', calibre: '.308 Win', detail: 'Model 46902', price: 22399, qty: 1, img: 'images/firearms/ruger-american-gen2.jpg', lic: 'hunt', features: FAM.rugerAmGen2.features, market: FAM.rugerAmGen2.market },
  { id: 'ruger-am-gen2-223', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger American Gen 2', calibre: '.223 Rem', detail: 'Model 46909', price: 20999.99, qty: 1, img: 'images/firearms/ruger-american-gen2.jpg', lic: 'hunt', features: FAM.rugerAmGen2.features, market: FAM.rugerAmGen2.market },
  { id: 'ruger-am-predator-gowild', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger American Predator Go Wild', calibre: '.243 Win', detail: 'Go Wild camo', price: 24959, qty: 1, img: 'images/firearms/ruger-american-predator.jpg', lic: 'hunt',
    features: ['Go Wild I-M Brush camo stock', 'Heavier tapered threaded barrel', 'Ruger Marksman adjustable trigger', 'Factory-installed one-piece scope rail', 'Purpose-built for varmint and predator work'],
    market: 'The Predator variant is the American that target shooters buy — the heavier barrel steadies it on the sticks, and .243 makes it a superb jackal, rooikat and springbok rifle.' },
  { id: 'ruger-am-3006', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger American', calibre: '.30-06 Springfield', detail: '', price: 16995, qty: 1, img: 'images/firearms/ruger-american-3006.jpg', lic: 'hunt',
    features: ['Ruger Marksman adjustable trigger', 'Power Bedding integral bedding blocks', 'Cold hammer-forged barrel', 'Lightweight synthetic stock', '.30-06 — the classic do-anything calibre'],
    market: 'The original American remains the definitive budget hunting rifle — millions sold on a simple recipe of real accuracy at an honest price. In .30-06 it will take anything in the Cape.' },
  { id: 'ruger-am-ranch-762', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger American Ranch', calibre: '7.62x39', detail: 'Compact ranch rifle', price: 20995, qty: 1, img: null, lic: 'hunt',
    features: ['Compact 16" barrel format', 'Threaded muzzle', 'Accepts Mini-30 style magazines', '7.62x39 — cheap, effective bushveld cartridge', 'Ideal farm and truck rifle'],
    market: 'The Ranch in 7.62x39 is the practical farmer\'s rifle — short, handy, cheap to feed, and plenty of punch for pigs and plains game at bush distances.' },
  { id: 'ruger-hawkeye-ftw-hunter', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger Hawkeye FTW Hunter', calibre: '6.5mm Creedmoor', detail: '', price: 24999, qty: 1, img: 'images/firearms/ruger-hawkeye-ftw.jpg', lic: 'hunt',
    features: ['Developed with the FTW Ranch shooting school', 'Adjustable laminate stock', 'Threaded, hammer-forged barrel with brake', 'Controlled round feed Hawkeye action', 'LC6 trigger'],
    market: 'The FTW Hunter was built to a shooting school\'s spec rather than a marketing brief, and it shows — a serious practical hunting rifle praised for balance and real-world accuracy.' },
  { id: 'ruger-hawkeye-ftw-predator', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger Hawkeye FTW Predator', calibre: '6.5mm Creedmoor', detail: '', price: 24550, qty: 1, img: 'images/firearms/ruger-hawkeye-ftw.jpg', lic: 'hunt',
    features: ['FTW Ranch collaboration — predator/target configuration', 'Adjustable laminate stock', 'Threaded heavy-contour barrel', 'Controlled round feed action', '6.5 Creedmoor — flat, efficient, easy on the shoulder'],
    market: 'Same FTW pedigree in a configuration aimed at longer sits and smaller targets. The controlled-feed Hawkeye action gives it an old-school reliability the spec sheet doesn\'t capture.' },
  { id: 'ruger-hawkeye-african-375', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger Hawkeye African', calibre: '.375 Ruger', detail: 'Model 37186', price: 50700, qty: 1, img: 'images/firearms/ruger-hawkeye-african.jpg', lic: 'hunt',
    features: ['.375 Ruger — H&H power from a standard-length action', 'Windage-adjustable express sights', 'Controlled round feed with fixed blade ejector', 'Ebony forend tip walnut stock', 'Muzzle brake included'],
    market: 'The .375 Ruger delivers full H&H ballistics in a handier rifle, and African PH circles have quietly adopted it. A legitimate dangerous-game rifle at a fraction of the safari-grade price tags.' },
  { id: 'ruger-precision-gen3-65', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger Precision Rifle Gen 3', calibre: '6.5mm Creedmoor', detail: '', price: 49995, qty: 1, img: null, lic: 'sport',
    features: ['The rifle that democratised chassis precision shooting', 'Folding, fully adjustable buttstock', 'Free-floated M-LOK handguard', 'Ruger Marksman adjustable trigger', 'Accepts AICS and M110 pattern magazines'],
    market: 'The RPR started the affordable precision revolution and the Gen 3 refined it. Club shooters across SA run these at PRS-style events — hard to beat for hits-per-rand at distance.' },
  { id: 'ruger-precision-338', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Ruger Precision Rifle', calibre: '.338 Lapua Mag', detail: 'Long-range precision', price: 64995, qty: 1, img: 'images/firearms/ruger-precision-338.jpg', lic: 'sport',
    features: ['.338 Lapua Magnum — serious 1,500m+ capability', 'Magnum-length precision action', 'Folding adjustable chassis stock', 'Heavy contour barrel with muzzle brake', 'Free-floated handguard'],
    market: 'For extreme long range on a factory-rifle budget, the RPR in .338 Lapua stands almost alone. Owners report ringing steel at distances that used to require custom builds costing three times as much.' },
  { id: 'ata-turqua-308', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'ATA Arms Turqua', calibre: '.308 Win', detail: 'Monte Carlo walnut stock', price: 22399.99, qty: 1, img: 'images/firearms/ata-turqua.png', lic: 'hunt', features: FAM.ataTurqua.features, market: FAM.ataTurqua.market },
  { id: 'ata-turqua-65cm', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'ATA Arms Turqua', calibre: '6.5mm Creedmoor', detail: 'Adjustable walnut stock', price: 22399.99, qty: 1, img: 'images/firearms/ata-turqua.png', lic: 'hunt', features: FAM.ataTurqua.features, market: FAM.ataTurqua.market },
  { id: 'ata-turqua-3006', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'ATA Arms Turqua', calibre: '.30-06 Springfield', detail: 'Adjustable walnut stock', price: 22499.99, qty: 1, img: 'images/firearms/ata-turqua.png', lic: 'hunt', features: FAM.ataTurqua.features, market: FAM.ataTurqua.market },
  { id: 'howa-m1500-270', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500', calibre: '.270 Win', detail: 'Blued, 22" barrel, synthetic', price: 14799, qty: 1, img: 'images/firearms/howa-m1500.png', lic: 'hunt', features: FAM.howaM1500.features, market: FAM.howaM1500.market },
  { id: 'howa-m1500-3006', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500', calibre: '.30-06 Springfield', detail: 'Blued, 22" threaded/capped', price: 14899.99, qty: 1, img: 'images/firearms/howa-m1500.png', lic: 'hunt', features: FAM.howaM1500.features, market: FAM.howaM1500.market },
  { id: 'howa-m1500-243-22', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500', calibre: '.243 Win', detail: 'Blued, 22" threaded/capped', price: 14850, qty: 1, img: 'images/firearms/howa-m1500.png', lic: 'hunt', features: FAM.howaM1500.features, market: FAM.howaM1500.market },
  { id: 'howa-m1500-243-24', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500', calibre: '.243 Win', detail: 'Blued, 24" threaded, synthetic', price: 15199, qty: 1, img: 'images/firearms/howa-m1500.png', lic: 'hunt', features: FAM.howaM1500.features, market: FAM.howaM1500.market },
  { id: 'howa-m1500-65cm', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500', calibre: '6.5mm Creedmoor', detail: 'Blued, threaded barrel', price: 15199, qty: 1, img: 'images/firearms/howa-m1500.png', lic: 'hunt', features: FAM.howaM1500.features, market: FAM.howaM1500.market },
  { id: 'howa-m1500-308-24', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500', calibre: '.308 Win', detail: '24" threaded barrel', price: 15899.99, qty: 1, img: 'images/firearms/howa-m1500.png', lic: 'hunt', features: FAM.howaM1500.features, market: FAM.howaM1500.market },
  { id: 'howa-m1500-308-26', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500', calibre: '.308 Win', detail: '26" threaded barrel', price: 16599, qty: 1, img: 'images/firearms/howa-m1500.png', lic: 'hunt', features: FAM.howaM1500.features, market: FAM.howaM1500.market },
  { id: 'howa-m1500-hb-223', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500 Heavy Barrel', calibre: '.223 Rem', detail: '24" heavy barrel, threaded/capped', price: 15899.99, qty: 1, img: 'images/firearms/howa-m1500-hb.png', lic: 'hunt', features: FAM.howaM1500HB.features, market: FAM.howaM1500HB.market },
  { id: 'howa-m1500-hb-22250', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500 Heavy Barrel', calibre: '.22-250 Rem', detail: '24" threaded barrel', price: 15799, qty: 1, img: 'images/firearms/howa-m1500-hb.png', lic: 'hunt', features: FAM.howaM1500HB.features, market: FAM.howaM1500HB.market },
  { id: 'howa-m1500-hb-300wm', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500 Heavy Barrel', calibre: '.300 Win Mag', detail: '26" heavy barrel, threaded/capped', price: 17499.99, qty: 2, img: 'images/firearms/howa-m1500-hb.png', lic: 'hunt', features: FAM.howaM1500HB.features, market: FAM.howaM1500HB.market },
  { id: 'howa-m1500-sb-300wm', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500 Semi-Bull', calibre: '.300 Win Mag', detail: '26" threaded, synthetic', price: 11999.99, qty: 1, img: 'images/firearms/howa-m1500-hb.png', lic: 'hunt', features: FAM.howaM1500HB.features, market: FAM.howaM1500HB.market },
  { id: 'howa-m1500-hb-300prc', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500 Heavy Barrel', calibre: '.300 PRC', detail: '26" heavy barrel, threaded', price: 17149.99, qty: 1, img: 'images/firearms/howa-m1500-hb.png', lic: 'hunt', features: FAM.howaM1500HB.features, market: FAM.howaM1500HB.market },
  { id: 'howa-m1500-hb-65prc', cat: 'rifles', type: 'Bolt-Action Rifle', name: 'Howa M1500 Heavy Barrel', calibre: '6.5 PRC', detail: '24" heavy barrel, threaded/capped', price: 17149.99, qty: 2, img: 'images/firearms/howa-m1500-hb.png', lic: 'hunt', features: FAM.howaM1500HB.features, market: FAM.howaM1500HB.market },

  /* ---- RIFLES — semi-auto / carbine ---- */
  { id: 'ruger-ar556', cat: 'rifles', type: 'Semi-Auto Rifle', name: 'Ruger AR-556', calibre: '5.56x45mm', detail: '16.1" barrel, model 8500', price: 31600, qty: 1, img: null, lic: 'sport',
    features: ['Ruger-built AR-15 with forged upper/lower', 'Cold hammer-forged 16.1" barrel', 'Adjustable stock, A2-style grip', 'Milspec-pattern parts compatibility', 'The value benchmark in factory ARs'],
    market: 'Ruger\'s AR-556 earned its reputation as the sensible entry into the AR platform — boringly reliable, correctly built, and backed by Ruger service. Sport shooters rate it the best value factory AR available locally.' },
  { id: 'ruger-sfar', cat: 'rifles', type: 'Semi-Auto Rifle', name: 'Ruger SFAR', calibre: '7.62x51 / .308', detail: '20" barrel, model 5611', price: 40995, qty: 1, img: 'images/firearms/ruger-sfar.jpg', lic: 'sport',
    features: ['.308 power in an AR-15 sized rifle — the SFAR\'s party trick', '20" barrel for full 7.62 ballistics', 'Two-port muzzle brake', 'Free-float M-LOK handguard', 'Significantly lighter than AR-10 class rifles'],
    market: 'The Small-Frame Autoloading Rifle genuinely surprised reviewers — .308 authority at AR-15 weight. For gong shooters wanting reach with semi-auto speed, it\'s one of the most interesting rifles of recent years.' },
  { id: 'sw-mp15-sport', cat: 'rifles', type: 'Semi-Auto Rifle', name: 'Smith & Wesson M&P15 Sport', calibre: '5.56 / .223', detail: '', price: 25999, qty: 1, img: null, lic: 'sport',
    features: ['The best-selling entry AR in America for a decade', 'Forged upper and lower receivers', 'Magpul MBUS rear sight', 'Chromoly 16" barrel', 'Full milspec parts compatibility'],
    market: 'The M&P15 Sport is the default recommendation for a first AR — proven by sheer volume, with every accessory on earth made to fit it. Simple, tough, and holds value well.' },
  { id: 'springfield-saint-edge', cat: 'rifles', type: 'Semi-Auto Rifle', name: 'Springfield Saint Edge', calibre: '5.56 NATO', detail: '16" barrel', price: 45999.99, qty: 1, img: null, lic: 'sport',
    features: ['Billet-machined receivers — the premium Saint tier', 'Light, rigid free-float handguard', 'Enhanced flat-faced trigger', 'Lightweight full-length build', 'Ships optic-ready'],
    market: 'The Edge is Springfield\'s answer to the semi-custom AR market: billet receivers and a genuinely good factory trigger. Reviewers place it a clear step above rack-grade ARs.' },
  { id: 'radical-slr-556', cat: 'rifles', type: 'Semi-Auto Rifle', name: 'Radical Firearms SLR', calibre: '5.56x45mm', detail: '16" forged', price: 22499, qty: 1, img: null, lic: 'sport',
    features: ['Forged receiver set', 'Free-float M-LOK rail', '16" barrel, milspec compatibility', 'The affordable route onto the AR platform', 'Huge upgrade path'],
    market: 'Radical built its name on getting shooters into an AR for the least money without cutting the corners that matter. A popular club starter rifle that upgrades happily over time.' },
  { id: 'ruger-pc-carbine', cat: 'rifles', type: 'Pistol-Calibre Carbine', name: 'Ruger PC Carbine', calibre: '9mm P', detail: 'Model 19100', price: 24100, qty: 1, img: 'images/firearms/ruger-pc-carbine.jpg', lic: 'sport', features: FAM.pcCarbine.features, market: FAM.pcCarbine.market },
  { id: 'ruger-pc-carbine-tact', cat: 'rifles', type: 'Pistol-Calibre Carbine', name: 'Ruger PC Carbine Tactical', calibre: '9mm P', detail: 'Model 19115', price: 26900, qty: 1, img: 'images/firearms/ruger-pc-carbine-tactical.jpg', lic: 'sport', features: FAM.pcCarbine.features, market: FAM.pcCarbine.market },

  /* ---- RIFLES — rimfire ---- */
  { id: 'ruger-1022', cat: 'rifles', type: 'Rimfire Rifle', name: 'Ruger 10/22 Carbine', calibre: '.22 LR', detail: 'The classic semi-auto rimfire', price: 11999.99, qty: 2, img: 'images/firearms/ruger-1022.jpg', lic: 'hunt',
    features: ['The world\'s most popular .22 semi-auto — 50+ years in production', 'Legendary 10-round rotary magazine', 'Hardwood stock, 18.5" barrel', 'Unmatched aftermarket upgrade ecosystem', 'The definitive plinker and first rifle'],
    market: 'Seven million sold and counting — the 10/22 is the rifle most shooters learned on. Cheap to run, endlessly customisable, and utterly proven. There is no safer firearm purchase.' },
  { id: 'ruger-precision-rimfire', cat: 'rifles', type: 'Rimfire Rifle', name: 'Ruger Precision Rimfire', calibre: '.22 LR', detail: '18" barrel', price: 17499.99, qty: 1, img: 'images/firearms/ruger-precision-rimfire.jpg', lic: 'sport',
    features: ['Scaled-down Ruger Precision Rifle in .22 LR', 'Adjustable precision chassis stock', 'Bolt throw mimics centrefire RPR for training', 'Takes 10/22 magazines', 'Ideal rimfire PRS/club competition rifle'],
    market: 'Rimfire precision competition has exploded in SA clubs, and this is one of its standard rifles — centrefire training for cents per round, praised as ludicrous fun for the money.' },
  { id: 'ruger-am-rimfire-17hmr', cat: 'rifles', type: 'Rimfire Rifle', name: 'Ruger American Rimfire', calibre: '.17 HMR', detail: '', price: 14499, qty: 1, img: 'images/firearms/ruger-american-rimfire.jpg', lic: 'hunt', features: FAM.rugerAmRimfire.features, market: FAM.rugerAmRimfire.market },
  { id: 'ruger-am-rimfire-22', cat: 'rifles', type: 'Rimfire Rifle', name: 'Ruger American Rimfire', calibre: '.22 LR', detail: '', price: 14550, qty: 1, img: 'images/firearms/ruger-american-rimfire.jpg', lic: 'hunt', features: FAM.rugerAmRimfire.features, market: FAM.rugerAmRimfire.market },
  { id: 'ruger-am-rimfire-thread', cat: 'rifles', type: 'Rimfire Rifle', name: 'Ruger American Rimfire Threaded', calibre: '.22 LR', detail: 'Threaded muzzle', price: 15415, qty: 1, img: 'images/firearms/ruger-american-rimfire.jpg', lic: 'hunt', features: FAM.rugerAmRimfire.features, market: FAM.rugerAmRimfire.market },
  { id: 'ruger-am-rimfire-gowild', cat: 'rifles', type: 'Rimfire Rifle', name: 'Ruger American Rimfire Go Wild', calibre: '.22 LR', detail: 'Go Wild camo', price: 17595, qty: 1, img: null, lic: 'hunt', features: FAM.rugerAmRimfire.features, market: FAM.rugerAmRimfire.market },
  { id: 'cz-457-lux', cat: 'rifles', type: 'Rimfire Rifle', name: 'CZ 457 Lux', calibre: '.22 LR', detail: 'Walnut, iron sights', price: 20999, qty: 2, img: null, lic: 'hunt',
    features: ['Turkish walnut stock with European-style comb', 'Tangent-adjustable iron sights', 'Fully adjustable trigger', 'Interchangeable barrel system', 'CZ rimfire accuracy pedigree'],
    market: 'CZ rimfires are the connoisseur\'s .22 — the 457 Lux pairs proper walnut and irons with a trigger and barrel that outshoot rifles costing far more. The .22 you keep for life.' },
  { id: 'tikka-t1x', cat: 'rifles', type: 'Rimfire Rifle', name: 'Tikka T1x', calibre: '.22 LR', detail: '20" barrel, 1/2x20 UNF thread', price: 17999, qty: 1, img: null, lic: 'hunt',
    features: ['Shares ergonomics and scope spacing with the T3x centrefire', 'Cross-over stock compatible with T3x aftermarket', 'Cold hammer-forged threaded barrel', 'Crisp single-stage trigger', 'Superb rimfire trainer'],
    market: 'The T1x brought Tikka\'s accuracy obsession to rimfire and immediately became a club favourite — a perfect understudy to a T3x hunting rifle and a serious rimfire competition rifle in its own right.' },
  { id: 'howa-m1100', cat: 'rifles', type: 'Rimfire Rifle', name: 'Howa M1100', calibre: '.22 LR', detail: '18" threaded/capped', price: 11999, qty: 1, img: null, lic: 'hunt',
    features: ['Howa build quality in a rimfire package', '18" threaded barrel — suppressor ready', 'Two-stage HACT-style trigger', 'Detachable magazine', 'Excellent value trainer'],
    market: 'Howa\'s rimfire carries the same honest-value DNA as the M1500 — a quiet achiever that punches above its price, especially suppressed.' },
  { id: 'sw-mp15-22', cat: 'rifles', type: 'Semi-Auto Rimfire', name: 'Smith & Wesson M&P15-22 MOE SL', calibre: '.22 LR', detail: '16.5" barrel', price: 19499, qty: 1, img: null, lic: 'sport',
    features: ['Dedicated .22 LR AR-platform trainer', 'Magpul MOE SL furniture', 'True AR controls and manual of arms', '25-round magazines available', 'Cheap AR training without centrefire costs'],
    market: 'The M&P15-22 is the standard answer to "how do I train AR skills affordably" — same controls, same drills, a tenth of the running cost. Club shooters burn through happy thousands of rounds with these.' },

  /* ---- HANDGUNS — pistols ---- */
  { id: 'glock-19-gen3', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Glock 19 Gen 3', calibre: '9mm P', detail: 'The proven compact 9mm', price: 9999.99, qty: 4, img: 'images/firearms/glock19.jpg', lic: 'sd', features: FAM.glock19.features,
    market: FAM.glock19.market + ' The Gen 3 is the classic recipe at the sharpest price — the most gun-per-rand in the cabinet.' },
  { id: 'glock-19-gen5', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Glock 19 Gen 5', calibre: '9mm P', detail: 'Fixed sights, front serrations', price: 15299.99, qty: 1, img: 'images/firearms/glock19.jpg', lic: 'sd', features: FAM.glock19.features,
    market: FAM.glock19.market + ' Gen 5 adds the improved Marksman barrel, ambidextrous slide stop and a grip without finger grooves.' },
  { id: 'glock-19-gen6', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Glock 19 Gen 6', calibre: '9mm P', detail: 'The newest generation G19', price: 18699.99, qty: 4, img: 'images/firearms/glock19.jpg', lic: 'sd', features: FAM.glock19.features,
    market: FAM.glock19.market + ' The newest generation brings Glock\'s latest refinements to the proven G19 formula — ask us in-store for the full rundown.' },
  { id: 'glock-43x', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Glock 43X', calibre: '9mm P', detail: 'Slimline everyday carry', price: 13699.99, qty: 3, img: null, lic: 'sd',
    features: ['Slimline frame — conceals dramatically better than a double-stack', '10+1 capacity in a slim grip', 'Full-size grip length for control, compact slide', 'Glock reliability in carry format', 'Huge holster ecosystem'],
    market: 'The 43X hit the sweet spot the whole industry chased — slim enough to disappear under a shirt, big enough to shoot properly. It has become the default concealed-carry recommendation in SA gun shops.' },
  { id: 'glock-45-mos', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Glock 45 MOS', calibre: '9mm P', detail: 'Optic-ready crossover', price: 18999, qty: 1, img: null, lic: 'sd',
    features: ['Crossover build: full-size grip + compact slide', 'MOS — cut for red-dot optics', 'Gen 5 Marksman barrel and controls', '17+1 capacity', 'Duty-proven configuration'],
    market: 'The G45 is what duty users asked for — the fast-handling compact slide over a full grip. With the MOS cut, it\'s the ready-made red-dot pistol, and reviews consistently rank it among the most shootable Glocks ever.' },
  { id: 'glock-47-mos', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Glock 47 Gen 5 MOS', calibre: '9mm P', detail: 'Optic-ready full size', price: 17899, qty: 1, img: null, lic: 'sd',
    features: ['Developed for US Customs & Border Protection', 'Full-size frame and slide, MOS optic cut', 'Parts crossover with G19/G45 slides', 'Gen 5 trigger and barrel', '17+1 capacity'],
    market: 'The G47 slipped quietly into the range as the "agency Glock" and shooters who try one tend to keep it — full-size sight radius, Gen 5 refinement and red-dot ready from the factory.' },
  { id: 'cz-p09-nocturne', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'CZ P-09 Compact Nocturne', calibre: '9mm P', detail: '', price: 14499, qty: 3, img: 'images/firearms/cz-p09-nocturne.jpg', lic: 'sd', features: FAM.czP09.features, market: FAM.czP09.market },
  { id: 'cz-p09-nocturne-fde', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'CZ P-09 Compact Nocturne FDE', calibre: '9mm P', detail: 'Flat Dark Earth', price: 16499.99, qty: 1, img: null, lic: 'sd', features: FAM.czP09.features, market: FAM.czP09.market },
  { id: 'cz-p10f', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'CZ P-10 F', calibre: '9mm P', detail: 'Full-size striker-fired', price: 13999, qty: 1, img: 'images/firearms/cz-p10.jpg', lic: 'sd',
    features: ['Full-size striker-fired 19+1', 'Excellent factory trigger for a striker gun', 'CZ grip angle and ergonomics', 'Aggressive slide serrations', 'Cold hammer-forged barrel'],
    market: 'The P-10 F is widely regarded as one of the best-value full-size 9mms on the market — reviewers routinely call its trigger the best in the striker class at this price.' },
  { id: 'beretta-apx-centurion', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Beretta APX Centurion', calibre: '9mm P', detail: '', price: 8999.99, qty: 1, img: null, lic: 'sd',
    features: ['Mid-size APX — duty capability, carry footprint', 'Full-slide serrations for easy manipulation', 'Modular chassis with swappable backstraps', '15+1 capacity', 'Beretta military-trials pedigree'],
    market: 'The APX came out of Beretta\'s army-trials programme and the Centurion size is its practical sweet spot. At this price point it\'s one of the strongest value defensive pistols in the cabinet.' },
  { id: 'taurus-g3c', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Taurus G3C', calibre: '9mm P', detail: 'Black, 12rd, 3 magazines', price: 8995, qty: 1, img: null, lic: 'sd',
    features: ['Compact 12+1 9mmP', 'Ships with THREE magazines', 'Restrike trigger capability', 'Modern Taurus QC — a different company than a decade ago', 'The budget carry benchmark'],
    market: 'The G3C forced the industry to take budget pistols seriously — American reviewers put tens of thousands of rounds through them with startlingly few issues. Three mags in the box seals the value case.' },
  { id: 'sig-p320-m17', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Sig Sauer P320 M17', calibre: '9mm P', detail: 'US Army service pistol', price: 26999, qty: 1, img: null, lic: 'sd',
    features: ['The US Army\'s M17 service pistol', 'Modular fire-control unit — one licence, many configurations*', 'Optic-ready slide with plate system', 'Coyote-tan military finish', 'SIGLITE night sights'],
    market: 'Winning the US military contract made the M17 an instant icon. Owners praise the trigger and the modularity; collectors buy it for what it represents. (*Configuration changes subject to SA licensing rules — ask us.)' },
  { id: 'springfield-echelon', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Springfield Echelon', calibre: '9mm P', detail: 'U-notch sights, threaded barrel', price: 21999, qty: 1, img: null, lic: 'sd',
    features: ['Central Operating Group — serialised removable chassis', 'Class-leading direct-mount optics system (no plates)', 'Threaded barrel from the factory', 'U-notch high-visibility sights', 'Adaptive grip texture'],
    market: 'The Echelon is Springfield\'s cleanest-sheet design in years and reviewers have been effusive — particularly about the optics mounting system, which many call the best in the industry.' },
  { id: 'springfield-xd-service', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Springfield XD Service', calibre: '9mm P', detail: 'With 3x 16rd magazines', price: 13099, qty: 1, img: null, lic: 'sd',
    features: ['Grip safety + trigger safety combination', '16+1 capacity, ships with three magazines', 'Point-and-shoot ergonomics', 'Proven service-pistol track record', 'Outstanding package value'],
    market: 'The XD has been a quiet workhorse of SA gun safes for two decades — the grip safety wins over shooters who want one more layer of mechanical assurance, and the three-mag bundle is real value.' },
  { id: 'girsan-mcr9', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Girsan MC R9', calibre: '9mm P', detail: '', price: 11500, qty: 1, img: null, lic: 'sd',
    features: ['Full-size Turkish 9mmP', 'Steel-reinforced polymer frame', 'Generous capacity', 'Affordable entry to centrefire pistol shooting', 'Growing local parts support'],
    market: 'Girsan has ridden Turkey\'s manufacturing boom into serious credibility — the MC R9 offers a lot of pistol for the money and has been well received as a range and home-defence starter.' },
  { id: 'ruger-max9', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Ruger Max-9 Long', calibre: '9mm P', detail: '4" barrel, model 3507', price: 13995, qty: 2, img: 'images/firearms/ruger-max9.jpg', lic: 'sd',
    features: ['Micro-compact with 12+1 capacity', '4" barrel — extra velocity and sight radius', 'Optic-ready slide', 'Tritium fibre-optic front sight', 'Thin, carry-friendly profile'],
    market: 'The Max-9 is Ruger\'s entry in the micro-nine wars and a strong one — reviewers highlight the usable sights and optic cut at a price the big names struggle to match.' },
  { id: 'ruger-american-duty', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Ruger American Duty', calibre: '9mm P', detail: '', price: 15659, qty: 1, img: null, lic: 'sd',
    features: ['Full-size duty pistol', 'Modular wrap-around grip system', 'Genuinely ambidextrous controls', 'Novak-style 3-dot sights', 'Built to US duty-trial specs'],
    market: 'Ruger\'s American Pistol was built for military trials and it shows in the over-engineering — a tank of a duty gun that shooters describe as soft-shooting and utterly dependable.' },
  { id: 'ruger-american-compact', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Ruger American Compact', calibre: '9mm P', detail: 'Model 8639', price: 17780, qty: 1, img: null, lic: 'sd',
    features: ['Compact version of the duty American', 'Modular backstraps', 'Ambidextrous slide stop and mag release', 'Duty-grade build in carry size', 'Soft recoil character'],
    market: 'All the American Duty\'s trial-grade engineering, shrunk for carry — a solid, underrated choice that owners consistently describe as more shootable than its size suggests.' },
  { id: 'ruger-ec9s', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Ruger EC9s', calibre: '9mm P', detail: 'FDE frame, model 3297', price: 11349, qty: 1, img: 'images/firearms/ruger-ec9s.jpg', lic: 'sd',
    features: ['Ultra-slim single-stack 9mmP', 'Integral machined sights — nothing to snag or shift', 'Featherweight for all-day carry', 'Simple, proven blowback-free design', 'Budget carry classic'],
    market: 'The EC9s is the honest budget carry gun — small, light, reliable and cheap enough that there\'s no excuse to leave it at home. A massive seller for exactly those reasons.' },
  { id: 'ruger-security9', cat: 'handguns', type: 'Semi-Auto Pistol', name: 'Ruger Security-9', calibre: '9mm P', detail: 'Model 3810', price: 11995, qty: 2, img: 'images/firearms/ruger-security9.jpg', lic: 'sd',
    features: ['Mid-size 15+1 9mmP', 'Secure Action hammer-fired mechanism', 'Simple takedown and maintenance', 'Rail for light/laser', 'Outstanding price-to-capability ratio'],
    market: 'Named after Ruger\'s classic Security Six ethos: honest protection at an honest price. The Security-9 routinely tops "best budget 9mm" lists and makes an excellent first home-defence pistol.' },

  /* ---- HANDGUNS — revolvers ---- */
  { id: 'ruger-super-blackhawk', cat: 'handguns', type: 'Revolver', name: 'Ruger Super Blackhawk', calibre: '.44 Mag', detail: '7.5" blued, model 0802', price: 32999, qty: 1, img: 'images/firearms/ruger-super-blackhawk.jpg', lic: 'hunt',
    features: ['The classic single-action .44 Magnum hunting revolver', '7.5" barrel for full magnum ballistics', 'Massive Ruger cylinder frame — built for heavy loads', 'Adjustable target sights', 'Handgun hunting icon'],
    market: 'Fifty years of handgun hunters have trusted the Super Blackhawk to digest full-house .44 loads forever. It\'s the revolver equivalent of a farm bakkie — it simply cannot be worn out.' },

  /* ---- SHOTGUNS ---- */
  { id: 'beretta-686-sp1', cat: 'shotguns', type: 'Over & Under Shotgun', name: 'Beretta 686 Silver Pigeon I Sport', calibre: '12 GA', detail: '30" barrels', price: 55999, qty: 1, img: null, lic: 'hunt',
    features: ['Beretta\'s legendary low-profile 686 boxlock action', 'Steelium barrels, 30" sporting configuration', 'Oil-finished select walnut', 'Interchangeable chokes', 'The world\'s best-selling premium O/U line'],
    market: 'Ask any clay club: the Silver Pigeon is the gun half the field shoots and the other half wishes they did. Hundreds of thousands of rounds between services is normal. The definitive sporting O/U.' },
  { id: 'beretta-1301-tactical', cat: 'shotguns', type: 'Semi-Auto Shotgun', name: 'Beretta 1301 Tactical', calibre: '12 GA', detail: '', price: 25999, qty: 1, img: null, lic: 'sd',
    features: ['BLINK gas system — cycles 36% faster than rivals', 'The professional\'s choice in defensive semi-autos', 'Oversized tactical controls', 'Ghost ring sights, rail for optics', 'Light, fast-pointing build'],
    market: 'The 1301 is the darling of the defensive shotgun world — instructors and competitors treat it as the benchmark semi-auto. Its speed of cycling has to be felt to be believed.' },
  { id: 'beretta-a300-patrol', cat: 'shotguns', type: 'Semi-Auto Shotgun', name: 'Beretta A300 Ultima Patrol', calibre: '12 GA', detail: 'Grey, 19", MB choke, 7+1', price: 43299, qty: 1, img: null, lic: 'sd',
    features: ['A300 gas system — soft-shooting and reliable', '7+1 capacity, 19" barrel', 'Mobil choke compatibility', 'Enlarged controls and loading port', 'The value route into a Beretta defensive semi'],
    market: 'The Ultima Patrol took the 1301\'s mission and made it more attainable — American reviewers immediately rated it one of the best value defensive shotguns available.' },
  { id: 'benelli-m2-sp', cat: 'shotguns', type: 'Semi-Auto Shotgun', name: 'Benelli M2 SP', calibre: '12 GA', detail: '26" semi-auto', price: 42499, qty: 1, img: null, lic: 'hunt',
    features: ['Benelli\'s famous Inertia-Driven system — no gas fouling', 'Runs clean for thousands of rounds', 'Lightning-fast cycling', '26" barrel sporting configuration', 'Comfortech-era recoil management'],
    market: 'The M2 is the wingshooter\'s workhorse — the inertia action shrugs off dirt, weather and neglect that would stop gas guns. Waterfowlers and sport shooters treat them as unkillable.' },
  { id: 'mossberg-940-jm', cat: 'shotguns', type: 'Semi-Auto Shotgun', name: 'Mossberg 940 JM Pro', calibre: '12 GA', detail: '24", gold/black, 9+1', price: 24699.99, qty: 1, img: null, lic: 'sport',
    features: ['Developed with speed legend Jerry Miculek', '9+1 capacity, competition loading port', 'Gas system runs 1,500+ rounds between cleanings', 'Fibre-optic front sight, stock spacers', 'Ready for 3-Gun out of the box'],
    market: 'The 940 JM Pro is the affordable competition semi-auto done right — Miculek\'s input shows in the loading port and controls. 3-Gun and practical shotgun shooters rate it a giant killer.' },
  { id: 'ata-sp-sporter', cat: 'shotguns', type: 'Over & Under Shotgun', name: 'ATA Arms SP Sporter', calibre: '12 GA', detail: '30" barrels', price: 29499, qty: 1, img: null, lic: 'hunt',
    features: ['30" sporting barrels with interchangeable chokes', 'Low-profile boxlock action', 'Selective single trigger, auto ejectors', 'Turkish walnut', 'The value sporting O/U of the moment'],
    market: 'ATA\'s SP line has been the quiet disruptor in clay sports — clubs are full of shooters who compared it to guns at twice the price and kept the change. Superb first sporting gun.' },
  { id: 'citadel-warthog', cat: 'shotguns', type: 'Semi-Auto Shotgun', name: 'Citadel Warthog', calibre: '12 GA', detail: 'Black, 4+1, 20" semi-auto', price: 5999.95, qty: 1, img: null, lic: 'sd',
    features: ['Semi-auto 12GA at a pump-gun price', '20" barrel, 4+1 capacity', 'Simple gas operation', 'Rail-ready receiver', 'Exceptional entry-level value'],
    market: 'The Warthog\'s pitch is simple: semi-auto firepower for the price of a budget pump. For a farm gun or first shotgun it\'s hard to argue with the arithmetic.' },
  { id: 'winchester-sxp-defender', cat: 'shotguns', type: 'Pump-Action Shotgun', name: 'Winchester SXP Xtreme Defender', calibre: '12 GA', detail: '5+1, Dark Earth', price: 17499.99, qty: 1, img: null, lic: 'sd',
    features: ['"The world\'s fastest pump" — inertia-assisted slide', 'Hard-chromed chamber and bore', '5+1 capacity, Dark Earth finish', 'Rotary bolt with four lugs', 'Defensive configuration with vents and rails'],
    market: 'Winchester\'s SXP earned its speed reputation honestly — the action practically pumps itself on recoil. The Xtreme Defender trim is a favourite home-defence pump in SA shops.' },
  { id: 'maverick-88', cat: 'shotguns', type: 'Pump-Action Shotgun', name: 'Mossberg Maverick 88', calibre: '12 GA', detail: '18.5" pump-action', price: 10199, qty: 1, img: null, lic: 'sd',
    features: ['Built on the immortal Mossberg 500 platform', '18.5" security barrel', 'Cross-bolt safety', 'Accepts most Mossberg 500 accessories', 'The definitive budget defensive pump'],
    market: 'The Maverick 88 is the answer to "cheapest shotgun I can absolutely rely on" — it\'s a Mossberg 500 built to a price, and it runs like one. Probably the most recommended budget defensive gun in the country.' },
  { id: 'panzer-bianca-x', cat: 'shotguns', type: 'Pump-Action Shotgun', name: 'Panzer Bianca X', calibre: '12 GA', detail: 'Pump-action, black', price: 7999, qty: 1, img: null, lic: 'sd',
    features: ['Modern tactical pump configuration', 'Robust Turkish build', 'Rail-ready for optics and lights', 'Excellent value defensive package', 'Backed by growing local support'],
    market: 'Panzer has become one of the volume names in affordable SA defensive shotguns — the Bianca X delivers the tactical pump formula at a price that keeps it moving off the shelf.' },
  { id: 'panzer-ss-red', cat: 'shotguns', type: 'Pump-Action Shotgun', name: 'Panzer Super Short', calibre: '12 GA', detail: 'Black & red', price: 8999, qty: 2, img: null, lic: 'sd', features: FAM.panzerSS.features, market: FAM.panzerSS.market },
  { id: 'panzer-ss-yellow', cat: 'shotguns', type: 'Pump-Action Shotgun', name: 'Panzer Super Short', calibre: '12 GA', detail: 'Black & yellow', price: 8999, qty: 1, img: null, lic: 'sd', features: FAM.panzerSS.features, market: FAM.panzerSS.market },
  { id: 'huntgroup-xrp010', cat: 'shotguns', type: 'Pump-Action Shotgun', name: 'Hunt Group XRP-010', calibre: '12 GA', detail: 'Black, 51cm barrel', price: 5899, qty: 1, img: null, lic: 'sd',
    features: ['51cm barrel defensive pump', 'Simple, serviceable Turkish build', 'Entry-level price point', 'Practical home and farm defence format', 'Light and quick-handling'],
    market: 'Hunt Group competes hard at the entry price point — a no-frills pump that does the job and leaves budget for ammunition and training, which matter more than the gun.' },
  { id: 'francolin-sxs', cat: 'shotguns', type: 'Side-by-Side Shotgun', name: 'Francolin 12GA Ejector', calibre: '12 GA', detail: '30" barrels, walnut', price: 17959.99, qty: 1, img: null, lic: 'hunt',
    features: ['Classic side-by-side field configuration', 'Automatic ejectors', '30" barrels, walnut furniture', 'Traditional wingshooting handling', 'Old-world character, accessible price'],
    market: 'For shooters drawn to the romance of a traditional double, the Francolin delivers the side-by-side experience — ejectors and all — without vintage-gun prices or vintage-gun gremlins.' }
];
