/* ============================================================
   WILDMAN ROBERTSON — CURRENT SPECIALS DATA
   Auto-generated by update-specials.ps1
   Last updated: June 2026
   ============================================================ */

var SPECIALS = {
  month: "June 2026",
  monthAfr: "Junie",
  updated: "27 June 2026",
  images: [
    {
      file: "Ruger-American-G22.jpg",
      title: "Ruger American Gen 2 Deals",
      price: "From R20,499",
      category: "firearms",
      desc: "Ruger American Gen 2 — 6.5 Creedmoor, .243 Win, .308 Win, .223 Rem. Prices exclusive to Robertson.",
      featured: true
    },
    {
      file: "Marlin.jpg",
      title: "Marlin 45-70 Govt Mod 1895 SBL",
      price: "R43,799",
      category: "firearms",
      desc: "Marlin 1895 SBL lever-action in .45-70 Govt. Stainless steel, laminate stock. While stocks last.",
      featured: true
    },
    {
      file: "Swarovski-Optics-June.jpg",
      title: "Swarovski Optics",
      price: "From R22,899",
      category: "optics",
      desc: "Swarovski Z3 4-12×50 BT 4W — R22,899 | Z5+ 5-25×56 BT 4W — R44,999 | DS 4-24×50 Gen 3 + FREE gift set (R10 000) — R109,999",
      featured: true
    },
    {
      file: "Simmons-Rangefinder.jpg",
      title: "Simmons Pro Hunter Rangefinder",
      price: "R2,899",
      category: "optics",
      desc: "Simmons Pro Hunter 6×2mm Laser Rangefinder. Includes battery. Perfect for hunting and long-range shooting.",
      featured: true
    },
    {
      file: "Winchester.jpg",
      title: "Winchester SXP Xtreme Defender",
      price: "R17,499",
      category: "firearms",
      desc: "Winchester SXP Xtreme Defender 5+1 Shotgun. Pump-action 12GA. Flat Dark Earth finish.",
      featured: false
    },
    {
      file: "Marlin-Winchester.jpg",
      title: "Marlin & Winchester Combo Card",
      price: "From R17,499",
      category: "firearms",
      desc: "Winchester SXP Xtreme Defender R17,499 + Marlin 45-70 Govt R43,799. Two great guns, one great shop.",
      featured: false
    },
    {
      file: "Swarovski-Optics-June2.jpg",
      title: "Swarovski Z5+ Range",
      price: "From R44,999",
      category: "optics",
      desc: "Swarovski Z5+ 5-25×56 BT 4W and Z5+i 3.5-18×50 BT4W-i. Premium Austrian precision for serious hunters.",
      featured: false
    },
    {
      file: "Magnum-Safes.jpg",
      title: "Magnum Safes — Wide Range In Stock",
      price: "From R1,099",
      category: "accessories",
      desc: "Handgun safes from R1,099. Up to 16-gun sliding safes at R28,999. SABS-approved. Multiple sizes in stock.",
      featured: false
    },
    {
      file: "Glary-Cases.jpg",
      title: "Glary Cases — Sale",
      price: "Rifle Case R999 (was R1,199)",
      category: "accessories",
      desc: "Glary Single Rifle Case 46\" Black — R999 (was R1,199). Handgun Case Black — R299 (was R349).",
      featured: false
    },
    {
      file: "Triggercam.jpg",
      title: "TriggerCam 2.1",
      price: "R8,999",
      category: "accessories",
      desc: "TriggerCam 2.1 — mount to any rifle scope and stream/record your shots. The ultimate hunter's camera.",
      featured: false
    },
    {
      file: "Drisafe.jpg",
      title: "RAM Drisafe Dehumidifier",
      price: "R69",
      category: "accessories",
      desc: "RAM Drisafe Moisture Absorber Dehumidifier — R69. Protect your firearms and gear from rust and moisture.",
      featured: false
    },
    {
      file: "Sako-Gamehead-Stock.jpg",
      title: "Sako Gamehead .308 150gr — In Stock",
      price: "POA",
      category: "ammo",
      desc: "Sako Gamehead .308 Win 150gr hunting ammunition now in stock at Wildman Robertson.",
      featured: false
    },
    {
      file: "CZ-Brand-Ambassador.jpg",
      title: "CZ Brand Ambassador Visit",
      price: "",
      category: "event",
      desc: "CZ Brand Ambassador visiting Wildman Robertson on 19 June 2026 at 12:30. Come feel the latest CZ firearms: Bren 2 MS, Scorpion Evo, P-10 C, TS 2 Racing Green, Shadow 2 Target, P-09 Noctune C, P-10 ported.",
      featured: false
    },
    {
      file: "Like-Father-Like-Son.jpg",
      title: "Father's Day — Dad's Choice",
      price: "",
      category: "event",
      desc: "Father's Day specials from Wildman Robertson. Give Dad what he really wants this year.",
      featured: false
    },
    {
      file: "June-16-holiday.jpeg",
      title: "Youth Day — 16 June",
      price: "",
      category: "notice",
      desc: "Youth Day holiday notice. Please check our trading hours.",
      featured: false
    }
  ]
};
